-- ====================================================
-- SMART KHATA MIGRATION V9: COMPREHENSIVE SCHEMA ALIGNMENT & DEFENSIVE COLUMNS
-- ====================================================

-- 1. SHOPS TABLE COMPREHENSIVE COLUMN ALIGNMENT
ALTER TABLE public.shops 
    ADD COLUMN IF NOT EXISTS phone TEXT,
    ADD COLUMN IF NOT EXISTS whatsapp_number TEXT,
    ADD COLUMN IF NOT EXISTS email TEXT,
    ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'BD',
    ADD COLUMN IF NOT EXISTS state TEXT,
    ADD COLUMN IF NOT EXISTS city TEXT,
    ADD COLUMN IF NOT EXISTS full_address TEXT,
    ADD COLUMN IF NOT EXISTS postal_code TEXT,
    ADD COLUMN IF NOT EXISTS business_type TEXT,
    ADD COLUMN IF NOT EXISTS currency_code TEXT DEFAULT 'BDT',
    ADD COLUMN IF NOT EXISTS gst_number TEXT,
    ADD COLUMN IF NOT EXISTS default_gst_rate NUMERIC(5,2) DEFAULT 18,
    ADD COLUMN IF NOT EXISTS logo_url TEXT,
    ADD COLUMN IF NOT EXISTS shop_photo_url TEXT,
    ADD COLUMN IF NOT EXISTS signature_url TEXT,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 2. CUSTOMERS TABLE COLUMN ALIGNMENT
ALTER TABLE public.customers 
    ADD COLUMN IF NOT EXISTS state TEXT;

-- 3. TRANSACTIONS TABLE COLUMN ALIGNMENT
ALTER TABLE public.transactions 
    ADD COLUMN IF NOT EXISTS ledger_photo_url TEXT,
    ADD COLUMN IF NOT EXISTS base_amount NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(12,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tax_type TEXT DEFAULT 'none';

-- RE-APPLY RLS POLICIES FOR SECURE MULTI-TENANCY
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
